POST http://localhost:8080/user/login/
Content-Type: application/json

{
  "email": "secondemail11",
  "password": "secondpassword"
}

###

POST http://localhost:8080/user/signup/
Content-Type: application/json

{
  "email": "secondemail11",
  "first_name": "secondhello",
  "last_name": "secondhello",
  "password": "secondpassword"
}

###
POST http://localhost:8080/signup/
Content-Type: application/x-www-form-urlencoded

first_name=John&last_name=Doe&email=johndoe@example.com&password=my_secure_password