POST http://localhost:8080/login/
Content-Type: application/json

{
  "email": "test",
  "password": "password"
}

###

POST http://localhost:8080/signup/
Content-Type: application/json

{
  "email": "secondemail11",
  "first_name": "secondhello",
  "last_name": "secondhello",
  "password": "secondpassword"
}